### ISSUE TITLE
Problem saving session

### ISSUE THREAD

**Issue by peter-si** [TheCynicalTeam/i3session#1]
Hi, I tried to save my session, but I'm getting this error:

```shell
❯ ./i3session save
Saving...
Traceback (most recent call last):
  File "./i3session", line 160, in <module>
    session['nodes'] = Tree.assign_processes(session['nodes'])
  File "./i3session", line 88, in assign_processes
    n['nodes'] = Tree.assign_processes(n['nodes'])
  File "./i3session", line 88, in assign_processes
    n['nodes'] = Tree.assign_processes(n['nodes'])
  File "./i3session", line 92, in assign_processes
    node = Node(n)
  File "./i3session", line 14, in __init__
    self.data = data
AttributeError: can't set attribute
```

I\m running arch and tried installing it via aur as i3session and also as i3session-git (which I think is for python2?). At first I was missing dependencies (which I thought would be installed when using aur). After I installed xdg  library, I came to this error, which I have no idea what to do with. I've also tried cloning your repo, but with the same result (above)

**Comment by CreativeCodeCat** [comment]
this bug should be squished in the update 2020.11.1-1

**Comment by CreativeCodeCat** [comment]
i am also working on a rewrite to fix the restore part :)
